/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package USUARIO;

import Clases_buscar.Buscar_paciente;
import Conexion_bd.Conectar;
import PDF.Reportin;
import java.awt.Event;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ERICK IVAN
 */
public class Paciente_existente extends javax.swing.JFrame {
public String idI;
public String usuario_doctor;//va a contener los datos de cada ventana nueva
   Conectar cu = new Conectar();
    Connection cnu = cu.conexion();
    
    /////////////////////////////////////
     String id_usuario="";///////////////
     String nombre="";///////////////////
     String edad="";  ///////////////////
     String diagnostico="";//////////////
     String obspreli="";/////////////////
     String obsfinales="";///////////////
     ////////////////////////////////////
         DefaultTableModel md_eliminar;
          DefaultTableModel md_reporte;
    String[][] data = {};
    String[] columnas = {"Paciente", "nombre","edad","diagnostico","observcion preliminar","observacion final","temperaturas 1","temperaturas 2","temperaturas 3"};
  
    public Paciente_existente() {
        initComponents();
          Image icon = new ImageIcon(getClass().getResource("/img/iconfehmex.png")).getImage();
setIconImage(icon);
  int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
       int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
 this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 500, 500);
//            this.setExtendedState(MAXIMIZED_BOTH);
           
         id_paciente();
        
        md_eliminar = new DefaultTableModel(data, columnas);
        md_reporte = new DefaultTableModel(data, columnas);
        tbl_eliminar.setModel(md_eliminar);
        tbl_reporte.setModel(md_reporte);
//         this.setSize(940 , 579);
//          this.setExtendedState(MAXIMIZED_BOTH);
//        panel_editar.setVisible(false);
//        panel_eliminar.setVisible(false);
//        panel_reporte.setVisible(false);
//        panel_paciente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        tabbedPaneHeader1 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelShadow3 = new org.edisoncor.gui.panel.PanelShadow();
        panel_reporte = new org.edisoncor.gui.panel.Panel();
        txt_buscar_reporte = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_reporte = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        panelShadow5 = new org.edisoncor.gui.panel.PanelShadow();
        panel_paciente = new org.edisoncor.gui.panel.Panel();
        jLabel13 = new javax.swing.JLabel();
        txt_paciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TXT_AREA = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        txt_nombre1 = new javax.swing.JTextField();
        txt_diagnostico1 = new javax.swing.JTextField();
        txt_edad1 = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        panelShadow6 = new org.edisoncor.gui.panel.PanelShadow();
        panel_editar = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_diagnostico = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_obspreli = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_obsfinales = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        panelShadow2 = new org.edisoncor.gui.panel.PanelShadow();
        panel_eliminar = new org.edisoncor.gui.panel.Panel();
        jLabel7 = new javax.swing.JLabel();
        txt_eliminar_paciente = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_eliminar = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelShadow7 = new org.edisoncor.gui.panel.PanelShadow();
        panel_paciente1 = new org.edisoncor.gui.panel.Panel();
        jLabel22 = new javax.swing.JLabel();
        txt_id_o_nombre = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_obs_preliminar_iniciar = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        txt_nombre_paciente_iniciar = new javax.swing.JTextField();
        txt_diagnostico_iniciar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        txt_edad_paciente_iniciar = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_id_paciente_iniciar = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_obs_finales_iniciar = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btn_modificar = new javax.swing.JMenuItem();
        btn_consultar = new javax.swing.JMenuItem();
        btn_eliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        lbl_usuario = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setColorPrimario(new java.awt.Color(0, 51, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.setGradiente(org.edisoncor.gui.panel.Panel.Gradiente.CIRCULAR);
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tapiz.jpg"))); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(700, 579));

        panelShadow3.setPreferredSize(new java.awt.Dimension(700, 579));

        panel_reporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reporte del paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        panel_reporte.setColorPrimario(new java.awt.Color(204, 204, 204));
        panel_reporte.setColorSecundario(new java.awt.Color(51, 204, 255));
        panel_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrtorio.jpg"))); // NOI18N
        panel_reporte.setPreferredSize(new java.awt.Dimension(641, 314));

        tbl_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_reporte);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar PDF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar paciente:");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nivel agua alto");

        jButton15.setBackground(new java.awt.Color(0, 204, 0));
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton16.setBackground(new java.awt.Color(204, 0, 0));
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nivel agua baja");

        javax.swing.GroupLayout panel_reporteLayout = new javax.swing.GroupLayout(panel_reporte);
        panel_reporte.setLayout(panel_reporteLayout);
        panel_reporteLayout.setHorizontalGroup(
            panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_reporteLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_reporteLayout.createSequentialGroup()
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(panel_reporteLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_buscar_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addGap(0, 381, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reporteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))))
        );
        panel_reporteLayout.setVerticalGroup(
            panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reporteLayout.createSequentialGroup()
                .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_reporteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jButton4)))
                    .addGroup(panel_reporteLayout.createSequentialGroup()
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_reporteLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShadow3Layout = new javax.swing.GroupLayout(panelShadow3);
        panelShadow3.setLayout(panelShadow3Layout);
        panelShadow3Layout.setHorizontalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_reporte, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow3Layout.setVerticalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_reporte, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Reporte paciente", panelShadow3);

        panel_paciente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        panel_paciente.setColorPrimario(new java.awt.Color(204, 204, 204));
        panel_paciente.setColorSecundario(new java.awt.Color(51, 153, 255));
        panel_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrtorio.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Paciente N°:");

        txt_paciente.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("NOMBRE:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("EDAD:   ");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("DIAGNOSTICO:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("OBSERVACIONES PRELIMINARES:");

        TXT_AREA.setColumns(20);
        TXT_AREA.setRows(5);
        TXT_AREA.setToolTipText("Describe la observación prliminar del paciente");
        jScrollPane5.setViewportView(TXT_AREA);

        jButton2.setText("EMPEZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_edad1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30 ", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nivel agua alto");

        jButton10.setBackground(new java.awt.Color(0, 204, 0));
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton9.setBackground(new java.awt.Color(204, 0, 0));
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nivel agua baja");

        javax.swing.GroupLayout panel_pacienteLayout = new javax.swing.GroupLayout(panel_paciente);
        panel_paciente.setLayout(panel_pacienteLayout);
        panel_pacienteLayout.setHorizontalGroup(
            panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pacienteLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pacienteLayout.createSequentialGroup()
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_pacienteLayout.createSequentialGroup()
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(panel_pacienteLayout.createSequentialGroup()
                                .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(0, 666, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panel_pacienteLayout.createSequentialGroup()
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_diagnostico1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_pacienteLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))))
        );
        panel_pacienteLayout.setVerticalGroup(
            panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pacienteLayout.createSequentialGroup()
                .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_pacienteLayout.createSequentialGroup()
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_pacienteLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diagnostico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShadow5Layout = new javax.swing.GroupLayout(panelShadow5);
        panelShadow5.setLayout(panelShadow5Layout);
        panelShadow5Layout.setHorizontalGroup(
            panelShadow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow5Layout.setVerticalGroup(
            panelShadow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Nuevo paciente", panelShadow5);

        panel_editar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        panel_editar.setColorPrimario(new java.awt.Color(204, 204, 204));
        panel_editar.setColorSecundario(new java.awt.Color(51, 204, 255));
        panel_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrtorio.jpg"))); // NOI18N
        panel_editar.setPreferredSize(new java.awt.Dimension(500, 579));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar paciente:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_id.setForeground(new java.awt.Color(255, 255, 255));
        label_id.setText("Identificador del paciente: 2");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Nombre:");

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Edad:    ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Diagnostico:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("observaciones preliminares:");

        txt_obspreli.setColumns(20);
        txt_obspreli.setRows(5);
        jScrollPane2.setViewportView(txt_obspreli);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Observaciones finales:");

        txt_obsfinales.setColumns(20);
        txt_obsfinales.setRows(5);
        jScrollPane3.setViewportView(txt_obsfinales);

        btn_guardar.setText("Guardar cambios");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nivel agua alto");

        jButton17.setBackground(new java.awt.Color(0, 204, 0));
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton18.setBackground(new java.awt.Color(204, 0, 0));
        jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nivel agua baja");

        javax.swing.GroupLayout panel_editarLayout = new javax.swing.GroupLayout(panel_editar);
        panel_editar.setLayout(panel_editarLayout);
        panel_editarLayout.setHorizontalGroup(
            panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editarLayout.createSequentialGroup()
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_editarLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_editarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4))
                    .addComponent(label_id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_editarLayout.createSequentialGroup()
                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_diagnostico))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_editarLayout.createSequentialGroup()
                        .addComponent(btn_guardar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_editarLayout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)))))
        );
        panel_editarLayout.setVerticalGroup(
            panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editarLayout.createSequentialGroup()
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_editarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(panel_editarLayout.createSequentialGroup()
                        .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_editarLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel18)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diagnostico)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(panel_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_editarLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_guardar))
                    .addGroup(panel_editarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelShadow6Layout = new javax.swing.GroupLayout(panelShadow6);
        panelShadow6.setLayout(panelShadow6Layout);
        panelShadow6Layout.setHorizontalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow6Layout.setVerticalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Editar  paciente", panelShadow6);

        panel_eliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        panel_eliminar.setColorPrimario(new java.awt.Color(204, 204, 204));
        panel_eliminar.setColorSecundario(new java.awt.Color(51, 204, 255));
        panel_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrtorio.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar paciente:");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tbl_eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_eliminar);

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nivel agua alto");

        jButton19.setBackground(new java.awt.Color(0, 204, 0));
        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton20.setBackground(new java.awt.Color(204, 0, 0));
        jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nivel agua baja");

        javax.swing.GroupLayout panel_eliminarLayout = new javax.swing.GroupLayout(panel_eliminar);
        panel_eliminar.setLayout(panel_eliminarLayout);
        panel_eliminarLayout.setHorizontalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_eliminarLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_eliminar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)))
        );
        panel_eliminarLayout.setVerticalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eliminarLayout.createSequentialGroup()
                .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_eliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_eliminar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jButton3)))
                    .addGroup(panel_eliminarLayout.createSequentialGroup()
                        .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_eliminarLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel20)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Eliminar paciente", panelShadow2);

        panel_paciente1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        panel_paciente1.setColorPrimario(new java.awt.Color(204, 204, 204));
        panel_paciente1.setColorSecundario(new java.awt.Color(51, 153, 255));
        panel_paciente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrtorio.jpg"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("N° del paciente o nombre:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("NOMBRE:");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("EDAD:   ");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setText("DIAGNOSTICO:");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("OBSERVACIONES PRELIMINARES:");

        txt_obs_preliminar_iniciar.setColumns(20);
        txt_obs_preliminar_iniciar.setRows(5);
        txt_obs_preliminar_iniciar.setToolTipText("Describe la observación prliminar del paciente");
        jScrollPane6.setViewportView(txt_obs_preliminar_iniciar);

        jButton7.setText("EMPEZAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt_nombre_paciente_iniciar.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nivel agua alto");

        jButton11.setBackground(new java.awt.Color(0, 204, 0));
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton12.setBackground(new java.awt.Color(204, 0, 0));
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nivel agua baja");

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setText("ID PACIENTE:");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setText("OBSERVACIONES FINALES:");

        txt_obs_finales_iniciar.setColumns(20);
        txt_obs_finales_iniciar.setRows(5);
        txt_obs_finales_iniciar.setToolTipText("Describe la observación prliminar del paciente");
        jScrollPane7.setViewportView(txt_obs_finales_iniciar);

        javax.swing.GroupLayout panel_paciente1Layout = new javax.swing.GroupLayout(panel_paciente1);
        panel_paciente1.setLayout(panel_paciente1Layout);
        panel_paciente1Layout.setHorizontalGroup(
            panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paciente1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_o_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)))
            .addComponent(jScrollPane6)
            .addGroup(panel_paciente1Layout.createSequentialGroup()
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_diagnostico_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre_paciente_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_id_paciente_iniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane7)
            .addGroup(panel_paciente1Layout.createSequentialGroup()
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paciente1Layout.createSequentialGroup()
                        .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_edad_paciente_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25))
                    .addComponent(jButton7))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_paciente1Layout.setVerticalGroup(
            panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paciente1Layout.createSequentialGroup()
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paciente1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_o_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jButton8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_paciente_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_paciente1Layout.createSequentialGroup()
                        .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_paciente1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel27)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nombre_paciente_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diagnostico_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_edad_paciente_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShadow7Layout = new javax.swing.GroupLayout(panelShadow7);
        panelShadow7.setLayout(panelShadow7Layout);
        panelShadow7Layout.setHorizontalGroup(
            panelShadow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_paciente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow7Layout.setVerticalGroup(
            panelShadow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_paciente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneHeader1.addTab("Iniciar prueba", panelShadow7);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Opciones");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevopaciente.png"))); // NOI18N
        jMenuItem1.setText("Nuevo paciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btn_modificar.setText("Modificar paciente");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jMenu1.add(btn_modificar);

        btn_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        btn_consultar.setText("Consultar paciente");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        jMenu1.add(btn_consultar);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar paciente");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jMenu1.add(btn_eliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        lbl_usuario.setText("---------------");
        jMenuBar1.add(lbl_usuario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
      System.out.println(""+  panel_editar.size());
      
    
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
  
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
       System.out.println(""+  panel_reporte.size());

  
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
         System.out.println(""+  panel_eliminar.size());

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String bus = txt_bus.getText();
            consultar(bus);    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
      if (evt.getKeyCode() == Event.ENTER) {
            String bus = txt_bus.getText();
            consultar(bus);
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
nombre=txt_nombre.getText();
edad=txt_edad.getText();
diagnostico=txt_diagnostico.getText();
obspreli=txt_obspreli.getText();
obsfinales=txt_obsfinales.getText();
 
    try {
            String ins = "UPDATE db_paciente set n_completo= ? , n_edad= ? ,n_diagnostico = ? , n_obspreliminar=? , n_obsfinales= ? where id_paciente = ?";
            PreparedStatement pst = cnu.prepareStatement(ins);
            pst.setString(1, nombre);
             pst.setString(2, edad);
              pst.setString(3, diagnostico);
               pst.setString(4, obspreli);
             pst.setString(5, obsfinales);
            pst.setString(6, id_usuario);
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Insercción Correcta", "Sistema ", JOptionPane.DEFAULT_OPTION, null);
txt_nombre.setText("");
txt_edad.setText("");
txt_diagnostico.setText("");
txt_obspreli.setText("");
txt_obsfinales.setText("");
id_usuario="";
            } else {
                JOptionPane.showMessageDialog(this, "La inserccion tuvo problemas", "Sistema ", JOptionPane.ERROR_MESSAGE);

            }
        } catch (SQLException ex) {
            Logger.getLogger(SENSORES.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 nombre_doctor();
        obspre=TXT_AREA.getText();
        if(obspre.equals("")){
            obspre="sin observacion preliminar";
        }
        System.out.println("id: "+idI);
        
        String ne=txt_nombre1.getText();
        String e=txt_edad1.getSelectedItem().toString();
        String d=txt_diagnostico1.getText();
        String usuario=idI;
        if(ne.equals("")||e.equals("")||d.equals("")){
            JOptionPane.showMessageDialog(txt_edad1, "ERROR verifique todos los campos","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            
            try {
                String ins = "INSERT INTO db_paciente (id_paciente,n_completo,n_edad,n_diagnostico,n_obspreliminar,n_obsfinales,n_temperatura,n_temperatura2,n_temperatura3,usuario_id) VALUES(?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement pst = cnu.prepareStatement(ins);
                pst.setString(1, txt_paciente.getText());
                pst.setString(2, ne);
                pst.setString(3, e);
                pst.setString(4, d);
                pst.setString(5, obspre);
                pst.setString(6, "no hay ninguna observacion final");
                pst.setString(7, "0");
                pst.setString(8, "0");
                 pst.setString(9, "0");
                pst.setString(10, usuario);
                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "excelente Paciente ingresado con exito");
                 txt_nombre1.setText("");
                 txt_edad1.setSelectedIndex(0);
                 txt_diagnostico1.setText("");
                 TXT_AREA.setText("");
id_paciente();
                } else {
                    JOptionPane.showMessageDialog(this, "Error, vuelva a intentarlo", "Sistema (diagnostico medico )", JOptionPane.ERROR_MESSAGE);

                }
            } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, "Error en la consulta por favor verifique que los datos ingresados sean correctos\n"
                           + "si el problema persiste favor de comunicarse con el encargado de este sistema", "Sistema (diagnostico medico)", JOptionPane.ERROR_MESSAGE);

                Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     
        if (tbl_eliminar.getRowCount() > 0) {

            try {
                int contador = tbl_eliminar.getSelectedRow();
                String usuario_id = (String) tbl_eliminar.getValueAt(contador, 0);
             
                
                try {
                    String ins = "DELETE from db_paciente  where id_paciente= ? ";
                    PreparedStatement pst = cnu.prepareStatement(ins);
                    pst.setString(1, usuario_id);
                   
                   int a= pst.executeUpdate();
                   if(a>0){
          JOptionPane.showMessageDialog(null, "Paciente eliminado con exito", "Sistema ", JOptionPane.DEFAULT_OPTION, null);
               DefaultTableModel ACTIVO = (DefaultTableModel) tbl_eliminar.getModel();
        for (int i = 0; i < tbl_eliminar.getRowCount(); i++) {
            ACTIVO.removeRow(i);
            i -= 1;
        }
                   }
                } catch (SQLException ex) {
                    Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (Exception e) {
                if (tbl_eliminar.getRowCount() > 0) {
                    JOptionPane.showMessageDialog(null, "Favor de seleccionar el paciente a eliminar", "Sistema ", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(tbl_eliminar, "No existe ningun paciente a eliminar", "Sistema ", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  DefaultTableModel ACTIVO = (DefaultTableModel) tbl_eliminar.getModel();
        for (int i = 0; i < tbl_eliminar.getRowCount(); i++) {
            ACTIVO.removeRow(i);
            i -= 1;
        }
        String bus = txt_eliminar_paciente.getText();
       
        
           String[] Registro = new String[9];
       
        String sql = "SELECT * FROM db_paciente where id_paciente='" + bus + "'" + "|| n_completo='" + bus + "'";
        Statement st;
        try {
            st = cnu.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registro[0] = rs.getString("id_paciente");
                Registro[1] = rs.getString("n_completo");
                Registro[2] = rs.getString("n_edad");
                Registro[3] = rs.getString("n_diagnostico");
                Registro[4] = rs.getString("n_obspreliminar");
                Registro[5] = rs.getString("n_obsfinales");
                Registro[6] = rs.getString("n_temperatura");
                Registro[7] = rs.getString("n_temperatura2");
                Registro[8] = rs.getString("n_temperatura3");
                String productos[] = {Registro[0], Registro[1],Registro[2], Registro[3], Registro[4], Registro[5], Registro[6],Registro[7],Registro[8]};
                md_eliminar.addRow(productos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel ACTIVO = (DefaultTableModel) tbl_reporte.getModel();
        for (int i = 0; i < tbl_reporte.getRowCount(); i++) {
            ACTIVO.removeRow(i);
            i -= 1;
        }
        String bus = txt_buscar_reporte.getText();
       
        
           String[] Registro = new String[9];
       
        String sql = "SELECT * FROM db_paciente where id_paciente='" + bus + "'" + "|| n_completo='" + bus + "'";
        Statement st;
        try {
            st = cnu.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registro[0] = rs.getString("id_paciente");
                Registro[1] = rs.getString("n_completo");
                Registro[2] = rs.getString("n_edad");
                Registro[3] = rs.getString("n_diagnostico");
                Registro[4] = rs.getString("n_obspreliminar");
                Registro[5] = rs.getString("n_obsfinales");
                Registro[6] = rs.getString("n_temperatura");
                Registro[7] = rs.getString("n_temperatura2");
                 Registro[8] = rs.getString("n_temperatura3");
                String productos[] = {Registro[0], Registro[1],Registro[2], Registro[3], Registro[4], Registro[5], Registro[6],Registro[7],Registro[8]};
                md_reporte.addRow(productos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "El reporte se encuentra en la carpeta");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     nombre_doctor();
     String id_paciente=txt_id_paciente_iniciar.getText();
        if(id_paciente.equals("")){
           JOptionPane.showMessageDialog(null, "No puedes iniciar porque no existe el Paciente");
        }else{
        SENSORES SEN=new SENSORES();
       SEN.lbl_nombre.setText(txt_nombre_paciente_iniciar.getText());
            SEN.nombre_paciente=txt_nombre_paciente_iniciar.getText();
            SEN.lbl_edad.setText("EDAD: "+txt_edad_paciente_iniciar.getText());
            SEN.edad=txt_edad_paciente_iniciar.getText();
            SEN.estado=txt_diagnostico_iniciar.getText();
            SEN.lbl_diagnostico.setText("DIAG."+txt_diagnostico_iniciar.getText());
            SEN.lbl_paci.setText("PACIENTE: "+ txt_id_paciente_iniciar.getText());
            SEN.No_paciente=txt_id_paciente_iniciar.getText();
            SEN.lbl_doctor.setText("DOCTOR: "+nombre_doctor);
            SEN.idI=idI;
            SEN.usuario_doctor=usuario_doctor;
               this.hide();   
            SEN.setVisible(true);
               
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String id_nombre=txt_id_o_nombre.getText();
        Buscar_paciente BP=new Buscar_paciente();
        BP.consulta(id_nombre);
        txt_id_paciente_iniciar.setText(""+BP.dato1);
        txt_nombre_paciente_iniciar.setText(""+BP.dato2);
        txt_edad_paciente_iniciar.setText(""+BP.dato3);
        txt_diagnostico_iniciar.setText(""+BP.dato4);
        txt_obs_preliminar_iniciar.setText(""+BP.dato5);
        txt_obs_finales_iniciar.setText(""+BP.dato6);
    }//GEN-LAST:event_jButton8ActionPerformed
String obspre="";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente_existente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente_existente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente_existente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente_existente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente_existente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TXT_AREA;
    private javax.swing.JMenuItem btn_consultar;
    private javax.swing.JMenuItem btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JMenuItem btn_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel label_id;
    public javax.swing.JMenu lbl_usuario;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow2;
    private org.edisoncor.gui.panel.PanelShadow panelShadow3;
    private org.edisoncor.gui.panel.PanelShadow panelShadow5;
    private org.edisoncor.gui.panel.PanelShadow panelShadow6;
    private org.edisoncor.gui.panel.PanelShadow panelShadow7;
    private org.edisoncor.gui.panel.Panel panel_editar;
    private org.edisoncor.gui.panel.Panel panel_eliminar;
    private org.edisoncor.gui.panel.Panel panel_paciente;
    private org.edisoncor.gui.panel.Panel panel_paciente1;
    private org.edisoncor.gui.panel.Panel panel_reporte;
    public org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader1;
    private javax.swing.JTable tbl_eliminar;
    private javax.swing.JTable tbl_reporte;
    private javax.swing.JTextField txt_bus;
    private javax.swing.JTextField txt_buscar_reporte;
    private javax.swing.JTextField txt_diagnostico;
    private javax.swing.JTextField txt_diagnostico1;
    private javax.swing.JTextField txt_diagnostico_iniciar;
    private javax.swing.JTextField txt_edad;
    private org.edisoncor.gui.comboBox.ComboBoxRect txt_edad1;
    private javax.swing.JTextField txt_edad_paciente_iniciar;
    private javax.swing.JTextField txt_eliminar_paciente;
    private javax.swing.JTextField txt_id_o_nombre;
    private javax.swing.JTextField txt_id_paciente_iniciar;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre_paciente_iniciar;
    private javax.swing.JTextArea txt_obs_finales_iniciar;
    private javax.swing.JTextArea txt_obs_preliminar_iniciar;
    private javax.swing.JTextArea txt_obsfinales;
    private javax.swing.JTextArea txt_obspreli;
    private javax.swing.JTextField txt_paciente;
    // End of variables declaration//GEN-END:variables

void consultar(String paciente){
    id_usuario=paciente;
    label_id.setText("Identificador del paciente: "+id_usuario);
    String sql = "SELECT * FROM db_paciente WHERE id_paciente='"+paciente+"'";
    
        Statement st;
        try {
            st = cnu.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                 nombre=rs.getString("n_completo");
                 edad=rs.getString("n_edad");
                 diagnostico=rs.getString("n_diagnostico");
                 obspreli=rs.getString("n_obspreliminar");
                 obsfinales=rs.getString("n_obsfinales");
                   
               
            }
txt_nombre.setText(""+nombre);

txt_edad.setText(""+edad);
txt_diagnostico.setText(""+diagnostico);
txt_obspreli.setText(""+obspreli);
txt_obsfinales.setText(""+obsfinales);

        } catch (SQLException ex) {
            Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
private void id_paciente() {
     int contador_id=0;
     int c=0;
        String[] Registro = new String[1];
        String sql = "SELECT id_paciente FROM db_paciente";
        Statement st;
        try {
            st = cnu.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registro[0] = rs.getString("id_paciente");
                c = Integer.parseInt(Registro[0]);
            }
            for (int i = 0; i <= c; i++) {
                contador_id = i + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_paciente.setText(""+contador_id);
    }
String nombre_doctor;
private void nombre_doctor(){
    
       
        String sql = "SELECT * FROM db_doctor where usuario_id='" + idI + "'" ;
        Statement st;
        try {
            st = cnu.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
               nombre_doctor = rs.getString("n_completo");
               idI=rs.getString("usuario_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Paciente_existente.class.getName()).log(Level.SEVERE, null, ex);
        }
  
}
}
